### ISSUE TITLE
console.log is annoying when using webpack dashboard

### ISSUE THREAD

**Issue by kazazor** [rohitlodha/html-webpack-inline-chunk-plugin#1]
When using [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) the `console.log` in [this line](https://github.com/rohitlodha/html-webpack-inline-chunk-plugin/blob/master/index.js#L22) is annoying and looks like that:

<img width="1406" alt="screen shot 2017-02-13 at 10 44 30 pm" src="https://cloud.githubusercontent.com/assets/1577655/22902520/02d1a9e6-f23e-11e6-9097-155c2fc2c2d3.png">

Maybe add a `quiet` mode for this plugin..?

**Comment by kazazor** [comment]
I created a PR that adds this mode, please let me know if it works for you and then we could merge and enjoy it :)

**Comment by kazazor** [comment]
@rohitlodha - would appreciate your input when you'll be able to take a look at it :)

**Comment by kazazor** [comment]
@rohitlodha - for every change and watch by webpack you print again your log and the problem gets worse:

<img width="1386" alt="screen shot 2017-02-19 at 10 54 46 pm" src="https://cloud.githubusercontent.com/assets/1577655/23106453/721183aa-f6f6-11e6-942c-94e8310bb7bf.png">

I would really appreciate your input here since I believe I provided here a solution which is pretty common in the webpack world and we only need to merge and publish it again.

Please respond so I could understand your thoughts about it and we could resolve it so this plugin would be even more useful.

**Comment by bogusfocused** [comment]
My apologies for the delay and thanks for introducing me to webpack dashboard! I have merged the commit and so closing this.
