### ISSUE TITLE
Add an option to not generate manifest.js file ?

### ISSUE THREAD

**Issue by KangdaOOLin** [rohitlodha/html-webpack-inline-chunk-plugin#3]
Is there a way to not generate `manifest.js` file while `webpack` compile ? If you can, you can add an option to let the user choose whether to generate the `manifest.js` file.

**Comment by bogusfocused** [comment]
It is generated by html plugin. I do not know anyway to stop it. You can ask in that [project](https://github.com/jantimon/html-webpack-plugin).
